[bosun]
exclude_ips = [ "192.168.168.168" ]
discovery = [ "docker" ]

[services]
name_match = "^/(.+)(-[0-9a-z]{7,14})$"

[haproxy]
bind_ip       = "192.168.168.168"
template_file = "views/haproxy.cfg"
config_file   = "/etc/haproxy/haproxy.cfg"
